package lexer

var multiCharOps = map[string]TokenType{
	// two char tokens
	"==": EQEQUAL,
	"!=": NOTEQUAL,
	"<=": LESSEQUAL,
	">=": GREATEREQUAL,
	">>": LEFTSHIFT,
	"**": DOUBLESTAR,
	"+=": PLUSEQUAL,
	"-=": MINEQUAL,
	"*=": STAREQUAL,
	"/=": SLASHEQUAL,
	"%=": PERCENTEQUAL,
	"&=": AMPEREQUAL,
	"|=": VBAREQUAL,
	"//": DOUBLESLASH,
	"@=": ATEQUAL,
	"->": RARROW,
	":=": COLONEQUAL,
	"^=": CIRCUMFLEXEQUAL,
	// three char tokens
	"<<=": LEFTSHIFTEQUAL,
	">>=": RIGHTSHIFTEQUAL,
	"**=": DOUBLESTAREQUAL,
	"//=": DOUBLESLASHEQUAL,
	"...": ELLIPSIS,
}

var singleCharOps = map[string]TokenType{
	"(": LPAR,
	")": RPAR,
	"[": LSQB,
	"]": RSQB,
	":": COLON,
	",": COMMA,
	";": SEMI,
	"+": PLUS,
	"-": MINUS,
	"*": STAR,
	"/": SLASH,
	"|": VBAR,
	"&": AMPER,
	"<": LESS,
	">": GREATER,
	"=": EQUAL,
	".": DOT,
	"%": PERCENT,
	"{": LBRACE,
	"}": RBRACE,
	"~": TILDE,
	"^": CIRCUMFLEX,
	"@": AT,
	"!": EXCLAMATION,
}
